/*
Author: Andressa da Silva Siqueira
MYSQL
*/

SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY lENGTH(CITY), CITY
LIMIT 1;

SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY) DESC,CITY
LIMIT 1